education/education/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^', include('profiles.urls', namespace='profiles')),
]

education/profiles/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
]

education/todo/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^wrong$', views.WrongView.as_view(), name='wrong_way'),

    # urls for add, update, view and delete lists
    url(r'^new$', views.CreateList.as_view(), name='add_list'),
    url(r'^shared$', views.SharedList.as_view(), name='shared_list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.ListDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.UpdateList.as_view(), name='update_list'),
    url(r'^(?P<pk>[0-9]+)/share/$',
        views.ShareList.as_view(), name='share_list'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteList.as_view(), name='delete_list'),


    # urls for add, update and delete tasks
    url(r'^(?P<list_pk>[0-9]+)/new$',
        views.CreateTask.as_view(), name='add_task'),
    url(r'^(?P<list_pk>[0-9]+)/(?P<pk>[0-9]+)$',
        views.UpdateTask.as_view(), name='update_task'),
    url(r'^(?P<list_pk>[0-9]+)/(?P<pk>[0-9]+)/delete$',
        views.DeleteTask.as_view(), name='delete_task'),
]

education/todo/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    """Model for creating list of future tasks"""

    name = models.CharField(max_length=100)
    users = models.ManyToManyField('profiles.MyUser', through='ListUsers')
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('todo:detail', kwargs={'pk': self.id})


class ListUsers(models.Model):
    """Middleware model with permissions."""

    PERMISSIONS = (
        ('a', 'Author'),
        ('r', 'Read only'),
        ('e', 'Read and edit'),
    )

    user = models.ForeignKey('profiles.MyUser')
    list = models.ForeignKey('List')
    permission = models.CharField(max_length=1, choices=PERMISSIONS)


class Task(models.Model):
    """Model for creating task of the list"""

    name = models.CharField(max_length=100)
    list = models.ForeignKey('List')
    description = models.TextField(blank=True, null=True)
    time = models.TimeField()
    completed = models.BooleanField(default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('todo:detail', kwargs={'pk': self.list.id})

education/todo/forms.py
from django import forms
from .models import List, Task
from django.forms.extras.widgets import Select


class ManageListForm(forms.ModelForm):
    """Form for creating new list."""

    class Meta:
        model = List
        fields = ['name']


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['list', 'completed']


class UpdateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ['list']


class ShareListForm(forms.Form):

    PERMISSIONS = (
        ('r', 'Read only'),
        ('e', 'View and edit'),
    )

    username = forms.CharField(label='Username for share', max_length=100)
    permissions = forms.ChoiceField(widget=Select, choices=PERMISSIONS)

education/todo/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from .forms import ManageListForm, AddTaskForm, UpdateTaskForm, ShareListForm
from django.core.urlresolvers import reverse_lazy
from django.core.urlresolvers import reverse
from .models import List, Task, ListUsers
from .decorators import LoginRequiredMixin, admin_or_permissions_required
from profiles.models import MyUser
from django.utils.decorators import method_decorator


class WrongView(generic.TemplateView):
    """Template view for access denied."""

    template_name = 'todo/wrong_way.html'


class IndexView(LoginRequiredMixin, generic.ListView):
    """View for printing all lists from database."""

    model = List
    template_name = 'todo/index.html'

    def get_queryset(self):
        user = self.request.user
        lists = user.list_set.filter(listusers__permission='a')
        return lists


class ListDetailView(LoginRequiredMixin, generic.DetailView):
    """View for printing details about list."""

    model = List
    template_name = 'todo/detail.html'
    cur_list = None
    perm = None

    def get_context_data(self, **kwargs):
        context = super(ListDetailView, self).get_context_data(**kwargs)
        author = self.cur_list.users.get(listusers__permission='a')
        perm = self.perm
        context['author'] = author
        context['perm'] = perm
        return context

    def get(self, request, *args, **kwargs):
        user = self.request.user
        list_pk = kwargs.get('pk', None)
        self.cur_list = get_object_or_404(List, pk=list_pk)
        try:
            self.perm = user.listusers_set.get(list=self.cur_list).permission
        except ListUsers.DoesNotExist:
            return HttpResponseRedirect('/todo/wrong')
        return super(ListDetailView, self).get(request, *args, **kwargs)


class SharedList(LoginRequiredMixin, generic.ListView):
    """View for printing all user's lists."""

    model = List
    template_name = 'todo/shared_list.html'

    def get_queryset(self):
        user = self.request.user
        lists = user.list_set.filter(listusers__permission__in=['r', 'e'])
        return lists


class CreateList(LoginRequiredMixin, generic.CreateView):
    """View for creating new list."""

    form_class = ManageListForm
    template_name = 'todo/add_list.html'

    def form_valid(self, form):
        new_list = form.save()
        user = self.request.user
        ListUsers.objects.create(user=user,
                                 list=new_list,
                                 permission='a')
        return super(CreateList, self).form_valid(form)


class UpdateList(LoginRequiredMixin, generic.UpdateView):
    """View for updating current list."""

    form_class = ManageListForm
    model = List
    template_name = 'todo/update_list.html'

    @method_decorator(admin_or_permissions_required('pk', 'a', 'e'))
    def get(self, request, *args, **kwargs):
        return super(UpdateList, self).get(request, *args, **kwargs)


class ShareList(generic.FormView):
    """Here must be view for sharing list from one user to another."""

    form_class = ShareListForm
    model = List
    template_name = 'todo/share_list.html'
    success_url = '/todo/'
    cur_list = None

    def get_list(self):
        list_pk = self.kwargs.get('pk', None)
        self.cur_list = get_object_or_404(List, pk=list_pk)

    @method_decorator(admin_or_permissions_required('pk', 'a'))
    def get(self, request, *args, **kwargs):
        return super(ShareList, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        name = form.cleaned_data.get('username', None)
        perms = form.cleaned_data.get('permissions', None)
        try:
            user = MyUser.objects.get(username=name)
        except MyUser.DoesNotExist:
            return HttpResponseRedirect('/todo/wrong')
        self.get_list()
        try:
            shared = user.listusers_set.get(list=self.cur_list)
        except ListUsers.DoesNotExist:
            shared = None
        if shared:
            if shared.permission != 'a':
                shared.permission = perms
                shared.save()
        else:
            ListUsers.objects.create(user=user,
                                     list=self.cur_list,
                                     permission=perms)
        return super(ShareList, self).form_valid(form)


class DeleteList(LoginRequiredMixin, generic.DeleteView):
    """View for deleting current list."""

    model = List
    template_name = 'todo/list_confirm_delete.html'
    success_url = reverse_lazy('todo:index')

    @method_decorator(admin_or_permissions_required('pk', 'a'))
    def get(self, request, *args, **kwargs):
        return super(DeleteList, self).get(request, *args, **kwargs)


class CreateTask(LoginRequiredMixin, generic.CreateView):
    """View for creating new Task of current list."""

    form_class = AddTaskForm
    template_name = 'todo/add_task.html'
    cur_list = None

    def get_list(self):
        list_pk = self.kwargs.get('list_pk', None)
        self.cur_list = get_object_or_404(List, pk=list_pk)

    def get_context_data(self, **kwargs):
        self.get_list()
        context = super(CreateTask, self).get_context_data(**kwargs)
        context['list'] = self.cur_list
        return context

    @method_decorator(admin_or_permissions_required('list_pk', 'a', 'e'))
    def get(self, request, *args, **kwargs):
        return super(CreateTask, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        self.get_list()
        form.instance.list = self.cur_list
        form.instance.completed = False
        return super(CreateTask, self).form_valid(form)


class UpdateTask(LoginRequiredMixin, generic.UpdateView):
    """View for updating current Task."""

    form_class = UpdateTaskForm
    model = Task
    template_name = 'todo/update_task.html'

    @method_decorator(admin_or_permissions_required('list_pk', 'a', 'e'))
    def get(self, request, *args, **kwargs):
        return super(UpdateTask, self).get(request, *args, **kwargs)


class DeleteTask(LoginRequiredMixin, generic.DeleteView):
    """View for deleting current Task."""

    model = Task
    template_name = 'todo/task_confirm_delete.html'

    @method_decorator(admin_or_permissions_required('list_pk', 'a', 'e'))
    def get(self, request, *args, **kwargs):
        return super(DeleteTask, self).get(request, *args, **kwargs)

    def get_success_url(self):
        list_pk = self.kwargs.get('list_pk', None)
        self.success_url = reverse('todo:detail', kwargs={
            'pk': list_pk,
        })
        return super(DeleteTask, self).get_success_url()

education/todo/templates/todo/add_list.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Add New List</h2>
{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <p>Please, fix errors and try again</p>
    </div>
{% endif %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Add' %}

    <a href="{% url 'todo:index' %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>



{% endblock %}

education/todo/templates/todo/add_task.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>All New Task</h2>
{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <p>Please, fix errors and try again</p>
    </div>
{% endif %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Add' %}

    <a href="{% url 'todo:detail' list.id %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>



{% endblock %}

education/todo/templates/todo/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load url from future %}
{% load bootstrap3 %}
{% bootstrap_css %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cover Template for Bootstrap</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="site-wrapper">

        <div class="site-wrapper-inner">

            <div class="cover-container">

                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">
                            {% if user.is_authenticated %}
                                <p>Welcome, <a href="{% url 'profiles:profile' user.id  %}">{{ user.username }}!</a></p>
                            {% else %}
                                <p>Welcome, guest!</p>
                            {% endif %}
                        </h3>
                        <nav>
                            {% if user.is_authenticated %}
                            <ul class="nav masthead-nav">
                                <li><a href="{% url 'profiles:index' %}">Main</a></li>
                                <li><a href="{% url 'todo:index' %}">My Lists</a></li>
                                <li><a href="{% url 'todo:shared_list' %}">Shared Lists</a></li>
                                <li><a href="{% url 'todo:add_list' %}">New List</a></li>
                                <li><a href="{% url 'profiles:logout' %}">Logout</a></li>
                            </ul>
                            {% else %}
                            <ul class="nav masthead-nav">
                                <li><a href="{% url 'profiles:index' %}">Main</a></li>
                                <li><a href="{% url 'profiles:register' %}">Sign Up</a></li>
                                <li><a href="{% url 'profiles:login' %}">Login</a></li>
                            </ul>
                            {% endif %}
                        </nav>
                    </div>
                    <h1 class="list_header">
                        {% block title %}
                        {% endblock %}
                    </h1>
                    <h4>
                        {% block author %}
                        {% endblock %}
                    </h4>
                </div>
                <div class="inner cover">
                    {% block content %}
                    {% endblock %}
                </div>

                <div class="mastfoot">
                    <div class="inner">
                        <p><a href="http://getbootstrap.com">Bootstrap</a></p>
                    </div>
                </div>

            </div>

        </div>

    </div>

</body>

education/todo/templates/todo/detail.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    {{ list.name }}
{% endblock %}

{% block author %}
    Created by: {{ author }}
    {% if perm == 'e' %}
        <p>You have rights to edit this list</p>
    {% elif perm == 'r'  %}
        <p>You have rights only to read this list</p>
    {% endif %}
{% endblock %}

{% block content %}

<p>Need to add task?</p>
<h4 class="list_nav">
    <a href="{% url 'todo:add_task' list.id %}" class="btn btn-success">
        Add Task
    </a>
</h4>

{% if list.task_set.all %}

<div class="row">
    <div class="col-md-2"><h4>Task title</h4></div>
    <div class="col-md-2"><h4>Time</h4></div>
    <div class="col-md-5"><h4>Description</h4></div>
    <div class="col-md-1"><h4>Completed</h4></div>
</div>
<hr/>
<div>
    {% for task in list.task_set.all %}
    <div class="row">
        <div class="col-md-2">
            <a href="{% url 'todo:update_task' list.id task.id %}">
                {{ task.name }}
            </a>
        </div>
        <div class="col-md-2"><p>{{ task.time }}</p></div>
        <div class="col-md-5"><p>{{ task.description }}</p></div>
        {% if task.completed %}
            <div class="col-md-1"><p><span
                    class="glyphicon glyphicon-ok" aria-hidden="true">
            </span></p></div>
        {% else %}
            <div class="col-md-1"><p><span
                    class="glyphicon glyphicon-remove" aria-hidden="true">
            </span></p></div>
        {% endif %}
        <div class="col-md-2">
            <a href="{% url 'todo:delete_task' list.id task.id %}">
                Delete
            </a>
        </div>
    </div>


    {% endfor %}
</div>

{% else %}

    <p>No tasks are created for this list.</p>

{% endif %}

<hr/>

<div class="row">
    <div class="col-md-4">
        <p>Here you can edit your list</p>
        <h4><a href="{% url 'todo:update_list' list.id %}" class="btn btn-warning">
            Update
        </a></h4>
    </div>
    <div class="col-md-4">
        <p>Don't need this list any more?</p>
        <h4><a href="{% url 'todo:delete_list' list.id %}" class="btn btn-danger">
            Delete
        </a></h4>
    </div>
    <div class="col-md-4">
        <p>Do you want to share list?</p>
        <h4><a href="{% url 'todo:share_list' list.id %}" class="btn btn-warning">
            Share
        </a></h4>
    </div>
</div>


{% endblock %}

education/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>My Lists</h2>
{% endblock %}

{% block content %}

{% if object_list %}

<div class="row">
    <div class="col-md-3"><h4>Date</h4></div>
    <div class="col-md-6"><h4>List name</h4></div>
    <div class="col-md-3"><h4>Delete?</h4></div>
</div>

<hr/>

<ul>
    {% for list in object_list %}

    <div class="row">
        <div class="col-md-3"><h4><p>{{ list.created_date }}</a></p></h4></div>
        <div class="col-md-6"><h4><a href="{% url 'todo:detail' list.id %}">{{ list.name }}</a></h4></div>
        <div class="col-md-3">
            <h4>
                <a href="{% url 'todo:delete_list' list.id %}" class="btn btn-danger">
                    Delete
                </a>
            </h4>
        </div>
    </div>



    {% endfor %}
</ul>
<hr/>

{% else %}

    <p>You are at ToDo list application. Here you can create and manage your lists.</p>
    <p>Do you want to start your first one?</p>
    <h4><a href="{% url 'todo:add_list'%}" class="btn btn-success">
        Add List
    </a></h4>

{% endif %}

{% endblock %}

education/todo/templates/todo/list_confirm_delete.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Delete List</h2>
{% endblock %}

{% block content %}

<p>Do you really want to delete it?</p>

<form action="" role="form" method="POST">

    {% csrf_token %}

    {% buttons submit='Delete' %}

    <a href="{% url 'todo:detail' list.id %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/todo/templates/todo/share_list.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Page for sharing</h2>
{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <p>Please, fix errors and try again</p>
    </div>
{% endif %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Add' %}

    <a href="{% url 'todo:index' %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/todo/templates/todo/shared_list.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Shared Lists</h2>
{% endblock %}

{% block content %}

{% if object_list %}

<div class="row">
    <div class="col-md-4"><h4>Date</h4></div>
    <div class="col-md-8"><h4>List name</h4></div>
</div>

<hr/>

<ul>
    {% for list in object_list %}

    <div class="row">
        <div class="col-md-3"><p>{{ list.created_date }}</a></p></div>
        <div class="col-md-9"><h4><a href="{% url 'todo:detail' list.id %}">{{ list.name }}</a></h4></div>
    </div>



    {% endfor %}
</ul>
<hr/>

{% else %}

    <p>You don't have any shared lists</p>

{% endif %}

{% endblock %}

education/todo/templates/todo/task_confirm_delete.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Delete Task</h2>
{% endblock %}

{% block content %}

<p>Do you really want to delete it?</p>

<form action="" role="form" method="POST">

    {% csrf_token %}

    {% buttons submit='Delete' %}

    <a href="{% url 'todo:detail' object.list.id %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/todo/templates/todo/update_list.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Edit List</h2>
{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <p>Please, fix errors and try again</p>
    </div>
{% endif %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <ul>

        {% bootstrap_form form layout="horizontal" %}

    </ul>

    {% buttons submit='Update' %}

    <a href="{% url 'todo:detail' list.id %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/todo/templates/todo/update_task.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Edit Task</h2>
{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <p>Please, fix errors and try again</p>
    </div>
{% endif %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <ul>

        {% bootstrap_form form layout="horizontal" %}

    </ul>

    {% buttons submit='Update' %}

    <a href="{% url 'todo:detail' object.list.id %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/todo/templates/todo/wrong_way.html
{% extends 'todo/base.html' %}

{% load bootstrap3 %}

{% block content %}

    <h2>You shall not pass!!!</h2>

{% endblock %}