education/education/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^', include('profiles.urls', namespace='profiles')),
]

education/profiles/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
]

education/todo/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^wrong$', views.WrongView.as_view(), name='wrong_way'),

    # urls for add, update, view and delete lists
    url(r'^new$', views.CreateList.as_view(), name='add_list'),
    url(r'^shared$', views.SharedList.as_view(), name='shared_list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.ListDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.UpdateList.as_view(), name='update_list'),
    url(r'^(?P<pk>[0-9]+)/share/$',
        views.ShareList.as_view(), name='share_list'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteList.as_view(), name='delete_list'),


    # urls for add, update and delete tasks
    url(r'^(?P<list_pk>[0-9]+)/new$',
        views.CreateTask.as_view(), name='add_task'),
    url(r'^(?P<list_pk>[0-9]+)/(?P<pk>[0-9]+)$',
        views.UpdateTask.as_view(), name='update_task'),
    url(r'^(?P<list_pk>[0-9]+)/(?P<pk>[0-9]+)/delete$',
        views.DeleteTask.as_view(), name='delete_task'),
]

education/profiles/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email=email,
            username=username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    alphanumeric = RegexValidator(
        r'^[0-9a-zA-Z]*$', message='Only alphanumeric characters are allowed.')
    username = models.CharField(unique=True, max_length=30,
                                validators=[alphanumeric])
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    # profile_image = models.ImageField(upload_to='uploads', blank=False,
    #                                   default='/static/images/avatar.png')
    user_bio = models.TextField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        return '%s %s'.format(self.last_name, self.first_name)

    def get_short_name(self):
        # The user is identified by their username
        return self.username

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        # Simplest possible answer: All admins are staff
        return self.is_admin

education/profiles/forms.py
from django import forms
from .models import MyUser
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email', 'username')

    def clean_username(self):
        username = self.cleaned_data['username']

        try:
            MyUser._default_manager.get(username=username)
        except MyUser.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user."""

    class Meta:
        model = MyUser
        fields = ('username', 'email', 'first_name', 'last_name',
                  'date_of_birth')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

education/profiles/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.views import generic
from django.core.urlresolvers import reverse
from .forms import UserCreationForm, UserChangeForm
from .models import MyUser


class IndexView(generic.base.TemplateView):
    template_name = 'profiles/index.html'


class RegisterFormView(generic.edit.FormView):
    """Register Class for new users."""

    form_class = UserCreationForm
    success_url = '/'
    template_name = 'profiles/register.html'

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(generic.edit.FormView):
    """Login Class to auth users."""

    form_class = AuthenticationForm
    template_name = 'profiles/login.html'
    success_url = '/todo/'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(generic.base.View):
    """Logout Class to logout users."""

    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class ProfileView(generic.edit.UpdateView):
    """Profile where user can change his info."""

    model = MyUser
    form_class = UserChangeForm
    template_name = 'profiles/profile.html'

    def get_success_url(self):
        return reverse('profiles:profile', kwargs={'pk': self.request.user.id})

    def form_valid(self, form):
        form.instance.password = self.request.user.password
        return super(ProfileView, self).form_valid(form)

education/profiles/templates/profiles/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load url from future %}
{% load bootstrap3 %}
{% bootstrap_css %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cover Template for Bootstrap</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="site-wrapper">

        <div class="site-wrapper-inner">

            <div class="cover-container">

                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">
                            {% if user.is_authenticated %}
                                <p>Welcome, <a href="{% url 'profiles:profile' user.id  %}">{{ user.username }}</a></p>
                            {% else %}
                                <p>Welcome</p>
                            {% endif %}
                        </h3>
                        <nav>
                            {% if user.is_authenticated %}
                            <ul class="nav masthead-nav">
                                <li><a href="{% url 'profiles:index' %}">Main</a></li>
                                <li><a href="{% url 'todo:index' %}">ToDo List</a></li>
                                <li><a href="{% url 'profiles:logout' %}">Logout</a></li>
                            </ul>
                            {% else %}
                            <ul class="nav masthead-nav">
                                <li><a href="{% url 'profiles:index' %}">Main</a></li>
                                <li><a href="{% url 'profiles:register' %}">Sign Up</a></li>
                                <li><a href="{% url 'profiles:login' %}">Login</a></li>
                            </ul>
                            {% endif %}
                        </nav>
                    </div>
                    <h1 class="list_header">
                        {% block title %}
                        {% endblock %}
                    </h1>
                </div>
                <div class="inner cover">
                    {% block content %}
                    {% endblock %}
                </div>

                <div class="mastfoot">
                    <div class="inner">
                        <p><a href="http://getbootstrap.com">Bootstrap</a></p>
                    </div>
                </div>

            </div>

        </div>

    </div>

</body>

education/profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}

{% block content %}

<h1>Hola</h1>

{% endblock %}

education/profiles/templates/profiles/login.html
{% extends 'profiles/base.html' %}

{% load bootstrap3 %}

{% block content %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Login' %}{% endbuttons %}

</form>

{% endblock %}

education/profiles/templates/profiles/profile.html
{% extends 'profiles/base.html' %}

{% load bootstrap3 %}

{% block title %}
    <h2>Profile</h2>
{% endblock %}

{% block content %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Save' %}

    <a href="{% url 'profiles:index' %}" class="btn btn-warning">
        Cancel
    </a>

    {% endbuttons %}

</form>

{% endblock %}

education/profiles/templates/profiles/register.html
{% extends 'profiles/base.html' %}

{% load bootstrap3 %}

{% block content %}

<form action="" role="form" method="POST">

    {% csrf_token  %}

    <div>

        {% bootstrap_form form layout="horizontal" %}

    </div>

    {% buttons submit='Register' %}{% endbuttons %}

</form>

{% endblock %}